# Generated by Django 5.0.8 on 2024-08-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alivaldiApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventariotienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_en_stock', models.IntegerField()),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
                ('actualizado_por', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'inventariotienda',
                'managed': False,
            },
        ),
    ]
