# Generated by Django 5.0.8 on 2024-08-22 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alivaldiApp', '0002_inventariotienda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rotacioninventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_movida', models.IntegerField()),
                ('fecha_movimiento', models.DateTimeField(blank=True, null=True)),
                ('realizado_por', models.CharField(max_length=100)),
                ('comentario', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rotacioninventario',
                'managed': False,
            },
        ),
    ]
