# Generated by Django 5.0.8 on 2024-08-29 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alivaldiApp', '0003_rotacioninventario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventariotienda',
            options={},
        ),
    ]
