# Generated by Django 5.0.8 on 2024-08-29 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alivaldiApp', '0004_alter_inventariotienda_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventariotienda',
            options={'managed': False},
        ),
    ]
