# Generated by Django 5.0.8 on 2024-09-28 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alivaldiApp', '0005_alter_inventariotienda_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tiposderopa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tiposderopa',
                'managed': False,
            },
        ),
    ]
