# Generated by Django 5.0.8 on 2024-10-08 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alivaldiApp', '0006_tiposderopa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorias',
            options={'managed': True},
        ),
    ]
